#!/bin/bash
exec < /dev/tty
# shellcheck disable=SC2046
# shellcheck disable=SC2062
# shellcheck disable=SC2126
if test $(git diff --cached | grep ^+.*console.log | wc -l) != 0; then
  read -p "Au moins un console.log est ajouté dans votre commit ! Êtes-vous certain de continuer ? [o/n]: " choix
  if [[ $choix == 'o' || $choix == 'O' ]]; then
    exit 0
  else
    exit 1
  fi
fi
# shellcheck disable=SC1073
# shellcheck disable=SC2046
if [  $(java -jar lib/google-java-format-1.10-all-deps.jar –replace src/*.java) ]; then
    exit 2;
    else
    exit  0
fi
# shellcheck disable=SC2046
if [  $(java -jar lib/spotbugs-4.3.0/lib/spotbugs.jar -textui src/*.class) ]; then
    exit 3
    else
    exit  0
fi
