#!/bin/bash
protected_branch='master'  
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $protected_branch = $current_branch ]  
then  
  
   read -p "Êtes-vous certain de continuer ? [o/n]: " choix
    if [[ $choix=='o'|| $choix=='O' ]]
        then
            exit 0 # push will execute
    fi
    exit 1 # push will not execute
else  
    exit 0 # push will execute
fi 