#!/bin/bash

exec < /dev/tty

# shellcheck disable=SC1073
# shellcheck disable=SC2046
if [  $(java -jar lib/google-java-format-1.10-all-deps.jar –replace src/*.java) ]; then
    exit 2;
    else
    exit  0
fi

# shellcheck disable=SC2046
if [  $(java -jar lib/spotbugs-4.3.0/lib/spotbugs.jar -textui src/*.class) ]; then
    exit 3
    else
    exit  0
fi